### ISSUE TITLE
Only responds via direct_mention and direct_message

### ISSUE THREAD

**Issue by ernestgwilsonii** [marchfederico/ciscospark-websocket-events#3]
These events do nothing:
**mention**
**message_received**
**ambient**

Example:
```
controller.hears('boom', 'mention,message_received,ambient', function (bot, message) {
    bot.reply(message, 'Kaboom!');
});
```

I would really like the bot to "hear" everything aka **ambient**

Any thoughts?
Thank you!

**Comment by marchfederico** [comment]
@ernestgwilsonii  My library takes the Cisco Spark message and sends it to the Botkit framework for parsing,  This looks like issue with the Botkit framework.  You will need to raise the issue on that repo.

**Comment by ernestgwilsonii** [comment]
Done.
(Opened an issue with Botkit)
REF: https://github.com/howdyai/botkit/issues/1060

Thank you @marchfederico 
Please close / resolve this issue from your repo.
and
Thank you for making **ciscospark-websocket-events**
